### ISSUE TITLE
Checking free disk space before torrent download

### ISSUE THREAD

**Issue by eyMarv** [anasty17/mirror-leech-telegram-bot#1058]
**Is your feature request related to a problem? Please describe.**
When downloading a 100gb torrent, but only having 30gb of free disk space, mirror-leech-telegram-bot will try to download it. E.g. on Heroku-similar platforms, the bot will crash.

**Describe the solution you'd like**
Check free disk space before starting leech.

**Comment by anasty17** [comment]
1st: Ur example is wrong and ur feature request is not valid because this is not group bot! Look at the free space before adding torrent!.

2nd: aria2c and qbittorrent will cancel the download automatically if no free space!.

U can go back with commits history and check STORAGE_THRESHOLD feature. It was implemented but i removed it with all group features! 

Please don't open issue again for group feature!

**Comment by eyMarv** [comment]
> 1st: Ur example is wrong and ur feature request is not valid because this is not group bot! Look at the free space before adding torrent!.
> 
> 2nd: aria2c and qbittorrent will cancel the download automatically if no enough free space!.
> 
> U can go back with commits history and check STORAGE_THRESHOLD feature. It was implemented but i removed it with all group features!
> 
> Please don't open issue again for group feature!

I appreciate that. Thanks for your answer! Great bot.
