### ISSUE TITLE
Seed issue

### ISSUE THREAD

**Issue by Awab01** [anasty17/mirror-leech-telegram-bot#156]
![20211211_120825](https://user-images.githubusercontent.com/95884934/145672719-497708d1-69fe-4933-980e-09dd85ded6c2.png)

After trying bot it seed torrent from rarbg perfectly
But torrent from private tracker not seed it stuck like that , is there any setting for private tracker?

**Comment by sunilroyy007** [comment]
> ![20211211_120825](https://user-images.githubusercontent.com/95884934/145672719-497708d1-69fe-4933-980e-09dd85ded6c2.png)
> 
> After trying bot it seed torrent from rarbg perfectly But torrent from private tracker not seed it stuck like that , is there any setting for private tracker?

Its not a good idea to seed private trackers with heroku because it restarts every 24 hours and sometimes randomly so if you download 1gb file and start seeding and bot restarts you need to download it again and start seeding, here also comes another issue if the torrent which you download has no leechers then it won't seed(i mean it wont show in your account as seeded and you will end up with hit and run warning+ban if repeated

You can try downloading same torrent again and see if it shows in your account as same or from different ip
I dont know if it shows in your ratio or not or it will end up 1+1=2gb total data to seed, i didn't tried

**Comment by anasty17** [comment]
No issues ... no one to seed his task
