### ISSUE TITLE
What to do for seeding

### ISSUE THREAD

**Issue by rkjai** [anasty17/mirror-leech-telegram-bot#455]
I had set it "True" on qbseed var but its not seeding ..what should I do now anasty

**Comment by Coolboyrajat** [comment]
> I had set it "True" on qbseed var but its not seeding ..what should I do now anasty

Believe me you regret doing that... because it take `100%` of your cpu usage & addition to that -> `seeding ratio` are not fix they are `undefined` & `time?` until you set the preferences according to you but if you set preferences many of them don't work. I'm currently running a bot so i know that.

Back to you problem ... if still you want to do that than B.O.L !!

It usually work without any problem give a `/restart` cmd to bot, if that not fix maybe owner can tell you why it not working

**Comment by anasty17** [comment]
> > I had set it "True" on qbseed var but its not seeding ..what should I do now anasty
> 
> Believe me you regret doing that... because it take `100%` of your cpu usage & addition to that -> `seeding ratio` are not fix they are `undefined` & `time?` until you set the preferences according to you but if you set preferences many of them don't work. I'm currently running a bot so i know that.
> 
> Back to you problem ... if still you want to do that than B.O.L !!
> 
> It usually work without any problem give a `/restart` cmd to bot, if that not fix maybe owner can tell you why it not working

Just don't reply again

**Comment by anasty17** [comment]
> I had set it "True" on qbseed var but its not seeding ..what should I do now anasty

Seeding status appears after using qbmirror or qbzipmirror?
If yes and no uploading.. then no peers to seed .. if not seeding status using qb cmds mirror only .. i wrote in readme which cmds will activate the seed check them ... if u r deploying with workflow and using gists for config.env then check if u have removed the commit id ... or do in ur bot /shell cat config.env to check ur vars if everything is ok and ignore the above reply
